import OpenAI from "openai";

// Lazy-initialized OpenAI client (only created when needed)
let openaiClient: OpenAI | null = null;

function getOpenAIClient(): OpenAI {
  if (!openaiClient) {
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) {
      throw new Error("OPENAI_API_KEY environment variable is not set");
    }
    openaiClient = new OpenAI({ apiKey });
  }
  return openaiClient;
}

export interface AIAnalysisResult {
  success: boolean;
  data?: unknown;
  error?: string;
  usage?: {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
  };
}

export async function runAIAnalysis(
  systemPrompt: string,
  userPrompt: string,
  options?: {
    model?: string;
    temperature?: number;
    maxTokens?: number;
  }
): Promise<AIAnalysisResult> {
  const model = options?.model || "gpt-4-turbo-preview";
  const temperature = options?.temperature ?? 0.1;
  const maxTokens = options?.maxTokens || 4096;

  try {
    const openai = getOpenAIClient();
    const response = await openai.chat.completions.create({
      model,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      temperature,
      max_tokens: maxTokens,
      response_format: { type: "json_object" },
    });

    const content = response.choices[0]?.message?.content;

    if (!content) {
      return {
        success: false,
        error: "No response content from AI",
      };
    }

    // Parse the JSON response
    const data = JSON.parse(content);

    return {
      success: true,
      data,
      usage: {
        promptTokens: response.usage?.prompt_tokens || 0,
        completionTokens: response.usage?.completion_tokens || 0,
        totalTokens: response.usage?.total_tokens || 0,
      },
    };
  } catch (error) {
    console.error("AI analysis error:", error);

    if (error instanceof SyntaxError) {
      return {
        success: false,
        error: "Failed to parse AI response as JSON",
      };
    }

    if (error instanceof OpenAI.APIError) {
      return {
        success: false,
        error: `OpenAI API error: ${error.message}`,
      };
    }

    return {
      success: false,
      error: error instanceof Error ? error.message : "Unknown error",
    };
  }
}

// Mock response for demo when API key is not available
export function getMockGapAssessmentResult() {
  return {
    workbook: {
      title: "Gap Assessment — Global Financial Crime Standards vs CIP/CDD Procedures",
      generated_at: new Date().toISOString().split("T")[0],
      sheets: [
        {
          name: "Summary",
          rows: [
            { Metric: "Total Standard Requirements", Value: 25 },
            { Metric: "Meets", Value: 15 },
            { Metric: "Partially Meets", Value: 5 },
            { Metric: "Does Not Meet (Gaps)", Value: 3 },
            { Metric: "Conflicts", Value: 1 },
            { Metric: "Exceeds", Value: 1 },
            { Metric: "Out of Scope / N/A", Value: 0 },
          ],
        },
        {
          name: "Gap_Details",
          rows: [
            {
              Gap_ID: "GAP-0001",
              Disposition: "Does Not Meet",
              Severity: "High",
              Standard_Requirement_ID: "STD-CIPCDD-0012",
              Standard_Requirement_Text: "Beneficial ownership must be verified for all legal entity customers with 25% or more ownership",
              Procedure_Reference_ID: "CIPCDD-0005",
              Gap_Description: "Procedures lack specific verification steps for beneficial ownership information",
              Recommended_Remediation: "Add explicit BO verification procedures including acceptable methods",
              Confidence: "High",
            },
            {
              Gap_ID: "GAP-0002",
              Disposition: "Partially Meets",
              Severity: "Medium",
              Standard_Requirement_ID: "STD-CIPCDD-0008",
              Standard_Requirement_Text: "Documentary verification must include government-issued ID with photo",
              Procedure_Reference_ID: "CIPCDD-0003",
              Gap_Description: "Photo requirement for ID verification is not explicitly stated",
              Recommended_Remediation: "Update procedures to explicitly require photo ID for documentary verification",
              Confidence: "High",
            },
            {
              Gap_ID: "GAP-0003",
              Disposition: "Does Not Meet",
              Severity: "Medium",
              Standard_Requirement_ID: "STD-CIPCDD-0015",
              Standard_Requirement_Text: "EDD procedures must include enhanced monitoring for high-risk customers",
              Procedure_Reference_ID: "N/A",
              Gap_Description: "Procedures do not address enhanced monitoring requirements for EDD customers",
              Recommended_Remediation: "Develop and document EDD monitoring procedures",
              Confidence: "High",
            },
            {
              Gap_ID: "GAP-0004",
              Disposition: "Meets",
              Severity: "Low",
              Standard_Requirement_ID: "STD-CIPCDD-0001",
              Standard_Requirement_Text: "Customer name must be collected for all new accounts",
              Procedure_Reference_ID: "CIPCDD-0001",
              Gap_Description: "Procedures fully address customer name collection requirements",
              Recommended_Remediation: "N/A - Requirement met",
              Confidence: "High",
            },
            {
              Gap_ID: "GAP-0005",
              Disposition: "Meets",
              Severity: "Low",
              Standard_Requirement_ID: "STD-CIPCDD-0002",
              Standard_Requirement_Text: "Date of birth must be collected for individual customers",
              Procedure_Reference_ID: "CIPCDD-0001",
              Gap_Description: "Procedures specify DOB collection for all individual customers",
              Recommended_Remediation: "N/A - Requirement met",
              Confidence: "High",
            },
            {
              Gap_ID: "GAP-0006",
              Disposition: "Meets",
              Severity: "Low",
              Standard_Requirement_ID: "STD-CIPCDD-0003",
              Standard_Requirement_Text: "Address must be collected for all customers",
              Procedure_Reference_ID: "CIPCDD-0001",
              Gap_Description: "Procedures require residential/business address collection",
              Recommended_Remediation: "N/A - Requirement met",
              Confidence: "High",
            },
            {
              Gap_ID: "GAP-0007",
              Disposition: "Meets",
              Severity: "Low",
              Standard_Requirement_ID: "STD-CIPCDD-0004",
              Standard_Requirement_Text: "Identification number (SSN/TIN) must be collected",
              Procedure_Reference_ID: "CIPCDD-0002",
              Gap_Description: "Procedures mandate SSN/TIN collection with proper handling",
              Recommended_Remediation: "N/A - Requirement met",
              Confidence: "High",
            },
            {
              Gap_ID: "GAP-0008",
              Disposition: "Partially Meets",
              Severity: "Medium",
              Standard_Requirement_ID: "STD-CIPCDD-0009",
              Standard_Requirement_Text: "Non-documentary verification must use at least two independent sources",
              Procedure_Reference_ID: "CIPCDD-0004",
              Gap_Description: "Procedures mention non-documentary methods but do not specify minimum sources",
              Recommended_Remediation: "Update to require minimum two independent verification sources",
              Confidence: "Medium",
            },
            {
              Gap_ID: "GAP-0009",
              Disposition: "Meets",
              Severity: "Low",
              Standard_Requirement_ID: "STD-CIPCDD-0005",
              Standard_Requirement_Text: "CIP records must be retained for 5 years after account closure",
              Procedure_Reference_ID: "CIPCDD-0010",
              Gap_Description: "Procedures specify 7-year retention period, exceeding requirement",
              Recommended_Remediation: "N/A - Requirement met",
              Confidence: "High",
            },
            {
              Gap_ID: "GAP-0010",
              Disposition: "Exceeds",
              Severity: "Low",
              Standard_Requirement_ID: "STD-CIPCDD-0006",
              Standard_Requirement_Text: "Customer risk rating must be assigned at onboarding",
              Procedure_Reference_ID: "CIPCDD-0006",
              Gap_Description: "Procedures require risk rating plus annual review, exceeding standard",
              Recommended_Remediation: "N/A - Requirement exceeded",
              Confidence: "High",
            },
            {
              Gap_ID: "GAP-0011",
              Disposition: "Partially Meets",
              Severity: "Medium",
              Standard_Requirement_ID: "STD-CIPCDD-0010",
              Standard_Requirement_Text: "Customer notice of CIP requirements must be provided",
              Procedure_Reference_ID: "CIPCDD-0007",
              Gap_Description: "Notice is provided but timing requirements not clearly specified",
              Recommended_Remediation: "Specify that notice must be given before or at account opening",
              Confidence: "Medium",
            },
            {
              Gap_ID: "GAP-0012",
              Disposition: "Meets",
              Severity: "Low",
              Standard_Requirement_ID: "STD-CIPCDD-0007",
              Standard_Requirement_Text: "OFAC screening must be performed at account opening",
              Procedure_Reference_ID: "CIPCDD-0008",
              Gap_Description: "Procedures mandate OFAC screening prior to account approval",
              Recommended_Remediation: "N/A - Requirement met",
              Confidence: "High",
            },
            {
              Gap_ID: "GAP-0013",
              Disposition: "Does Not Meet",
              Severity: "High",
              Standard_Requirement_ID: "STD-CIPCDD-0016",
              Standard_Requirement_Text: "PEP screening must include domestic and foreign PEPs",
              Procedure_Reference_ID: "CIPCDD-0008",
              Gap_Description: "Procedures only reference foreign PEPs, domestic PEPs not addressed",
              Recommended_Remediation: "Update screening procedures to include domestic PEP screening",
              Confidence: "High",
            },
            {
              Gap_ID: "GAP-0014",
              Disposition: "Meets",
              Severity: "Low",
              Standard_Requirement_ID: "STD-CIPCDD-0011",
              Standard_Requirement_Text: "Legal entity type must be documented",
              Procedure_Reference_ID: "CIPCDD-0005",
              Gap_Description: "Procedures require documentation of entity type with formation docs",
              Recommended_Remediation: "N/A - Requirement met",
              Confidence: "High",
            },
            {
              Gap_ID: "GAP-0015",
              Disposition: "Partially Meets",
              Severity: "Low",
              Standard_Requirement_ID: "STD-CIPCDD-0013",
              Standard_Requirement_Text: "Control person must be identified for legal entities",
              Procedure_Reference_ID: "CIPCDD-0005",
              Gap_Description: "Control person collection exists but criteria for identification unclear",
              Recommended_Remediation: "Clarify control person identification criteria in procedures",
              Confidence: "Medium",
            },
            {
              Gap_ID: "GAP-0016",
              Disposition: "Meets",
              Severity: "Low",
              Standard_Requirement_ID: "STD-CIPCDD-0014",
              Standard_Requirement_Text: "Nature of business must be documented for entities",
              Procedure_Reference_ID: "CIPCDD-0005",
              Gap_Description: "Procedures require nature of business and expected activity documentation",
              Recommended_Remediation: "N/A - Requirement met",
              Confidence: "High",
            },
            {
              Gap_ID: "GAP-0017",
              Disposition: "Conflict",
              Severity: "Medium",
              Standard_Requirement_ID: "STD-CIPCDD-0017",
              Standard_Requirement_Text: "EDD threshold is $1M in anticipated annual transactions",
              Procedure_Reference_ID: "CIPCDD-0009",
              Gap_Description: "Procedures specify $500K threshold, conflicting with global standard",
              Recommended_Remediation: "Align EDD threshold with global standard or document exception rationale",
              Confidence: "High",
            },
            {
              Gap_ID: "GAP-0018",
              Disposition: "Meets",
              Severity: "Low",
              Standard_Requirement_ID: "STD-CIPCDD-0018",
              Standard_Requirement_Text: "Adverse media screening must be performed for high-risk customers",
              Procedure_Reference_ID: "CIPCDD-0009",
              Gap_Description: "Procedures require adverse media screening as part of EDD",
              Recommended_Remediation: "N/A - Requirement met",
              Confidence: "High",
            },
            {
              Gap_ID: "GAP-0019",
              Disposition: "Meets",
              Severity: "Low",
              Standard_Requirement_ID: "STD-CIPCDD-0019",
              Standard_Requirement_Text: "Source of funds must be documented for high-risk accounts",
              Procedure_Reference_ID: "CIPCDD-0009",
              Gap_Description: "EDD procedures include source of funds documentation requirement",
              Recommended_Remediation: "N/A - Requirement met",
              Confidence: "High",
            },
            {
              Gap_ID: "GAP-0020",
              Disposition: "Meets",
              Severity: "Low",
              Standard_Requirement_ID: "STD-CIPCDD-0020",
              Standard_Requirement_Text: "CIP exceptions must be approved by compliance officer",
              Procedure_Reference_ID: "CIPCDD-0011",
              Gap_Description: "Procedures require compliance approval for all CIP exceptions",
              Recommended_Remediation: "N/A - Requirement met",
              Confidence: "High",
            },
            {
              Gap_ID: "GAP-0021",
              Disposition: "Partially Meets",
              Severity: "Medium",
              Standard_Requirement_ID: "STD-CIPCDD-0021",
              Standard_Requirement_Text: "Customer information must be updated at trigger events",
              Procedure_Reference_ID: "CIPCDD-0012",
              Gap_Description: "Trigger events defined but update process not fully documented",
              Recommended_Remediation: "Document step-by-step process for updating customer information",
              Confidence: "Medium",
            },
            {
              Gap_ID: "GAP-0022",
              Disposition: "Meets",
              Severity: "Low",
              Standard_Requirement_ID: "STD-CIPCDD-0022",
              Standard_Requirement_Text: "Reliance on third parties must be documented",
              Procedure_Reference_ID: "CIPCDD-0013",
              Gap_Description: "Third-party reliance agreements and certifications documented",
              Recommended_Remediation: "N/A - Requirement met",
              Confidence: "High",
            },
            {
              Gap_ID: "GAP-0023",
              Disposition: "Meets",
              Severity: "Low",
              Standard_Requirement_ID: "STD-CIPCDD-0023",
              Standard_Requirement_Text: "Suspicious activity must be escalated per SAR requirements",
              Procedure_Reference_ID: "CIPCDD-0014",
              Gap_Description: "SAR escalation procedures align with regulatory requirements",
              Recommended_Remediation: "N/A - Requirement met",
              Confidence: "High",
            },
            {
              Gap_ID: "GAP-0024",
              Disposition: "Meets",
              Severity: "Low",
              Standard_Requirement_ID: "STD-CIPCDD-0024",
              Standard_Requirement_Text: "Training on CIP/CDD must be provided annually",
              Procedure_Reference_ID: "CIPCDD-0015",
              Gap_Description: "Annual training requirement documented with tracking",
              Recommended_Remediation: "N/A - Requirement met",
              Confidence: "High",
            },
            {
              Gap_ID: "GAP-0025",
              Disposition: "Meets",
              Severity: "Low",
              Standard_Requirement_ID: "STD-CIPCDD-0025",
              Standard_Requirement_Text: "Quality assurance testing must be performed quarterly",
              Procedure_Reference_ID: "CIPCDD-0016",
              Gap_Description: "QA testing schedule and methodology documented",
              Recommended_Remediation: "N/A - Requirement met",
              Confidence: "High",
            },
          ],
        },
      ],
    },
  };
}

export function getMockAttributeExtractionResult() {
  return {
    workbook: {
      title: "CIP/CDD Onboarding — Attributes and Acceptable Documents",
      generated_at: new Date().toISOString().split("T")[0],
      sheets: [
        {
          name: "Attributes",
          rows: [
            {
              Source_File: "CIP_CDD_Procedures.docx",
              Attribute_ID: "A001",
              Attribute_Name: "Legal Entity Name",
              Category: "Entity Profile",
              Source: "CIP > Required Information > Entity Name",
              Source_Page: "para 5",
              Question_Text: "Verify that the legal entity name matches the formation documents and is correctly recorded in the system.",
              Notes: "Must match exactly as registered",
              Jurisdiction_ID: "ENT",
              RiskScope: "Base",
              IsRequired: "Y",
              DocumentationAgeRule: "",
              Group: "Entity",
            },
            {
              Source_File: "CIP_CDD_Procedures.docx",
              Attribute_ID: "A002",
              Attribute_Name: "Tax Identification Number",
              Category: "Entity Profile",
              Source: "CIP > Required Information > TIN",
              Source_Page: "para 7",
              Question_Text: "Confirm that a valid Tax Identification Number (EIN/TIN) has been obtained and verified.",
              Notes: "Required for US entities",
              Jurisdiction_ID: "ENT",
              RiskScope: "Base",
              IsRequired: "Y",
              DocumentationAgeRule: "",
              Group: "Entity",
            },
            {
              Source_File: "CIP_CDD_Procedures.docx",
              Attribute_ID: "A003",
              Attribute_Name: "Registered Address",
              Category: "Entity Profile",
              Source: "CIP > Required Information > Address",
              Source_Page: "para 8",
              Question_Text: "Verify that the registered business address is documented and matches official records.",
              Notes: "PO Box not acceptable as primary address",
              Jurisdiction_ID: "ENT",
              RiskScope: "Base",
              IsRequired: "Y",
              DocumentationAgeRule: "365",
              Group: "Entity",
            },
            {
              Source_File: "CIP_CDD_Procedures.docx",
              Attribute_ID: "A004",
              Attribute_Name: "Formation Documents",
              Category: "Documentation",
              Source: "CIP > Documentary Verification > Formation",
              Source_Page: "para 12",
              Question_Text: "Obtain and verify formation documents (Articles of Incorporation, Certificate of Formation, or equivalent).",
              Notes: "Must be certified or apostilled for foreign entities",
              Jurisdiction_ID: "ENT",
              RiskScope: "Base",
              IsRequired: "Y",
              DocumentationAgeRule: "",
              Group: "Entity",
            },
            {
              Source_File: "CIP_CDD_Procedures.docx",
              Attribute_ID: "A005",
              Attribute_Name: "Beneficial Owners (≥25%)",
              Category: "Ownership",
              Source: "CDD > Beneficial Ownership > Collection",
              Source_Page: "para 18",
              Question_Text: "Verify that all beneficial owners with 25% or greater ownership interest have been identified and documented.",
              Notes: "Include indirect ownership through intermediaries",
              Jurisdiction_ID: "ENT",
              RiskScope: "Base",
              IsRequired: "Y",
              DocumentationAgeRule: "",
              Group: "Beneficial Owner",
            },
            {
              Source_File: "CIP_CDD_Procedures.docx",
              Attribute_ID: "A006",
              Attribute_Name: "BO Identity Verification",
              Category: "Ownership",
              Source: "CDD > Beneficial Ownership > Verification",
              Source_Page: "para 20",
              Question_Text: "Confirm that identity verification has been completed for each beneficial owner using acceptable methods.",
              Notes: "Documentary or non-documentary methods acceptable",
              Jurisdiction_ID: "ENT",
              RiskScope: "Base",
              IsRequired: "Y",
              DocumentationAgeRule: "",
              Group: "Beneficial Owner",
            },
            {
              Source_File: "CIP_CDD_Procedures.docx",
              Attribute_ID: "A007",
              Attribute_Name: "Controlling Person",
              Category: "Ownership",
              Source: "CDD > Control Prong > Identification",
              Source_Page: "para 22",
              Question_Text: "Verify that the individual with significant control (control prong) has been identified if no 25% owner exists.",
              Notes: "Required when no individual meets 25% threshold",
              Jurisdiction_ID: "ENT",
              RiskScope: "Base",
              IsRequired: "Y",
              DocumentationAgeRule: "",
              Group: "Beneficial Owner",
            },
            {
              Source_File: "CIP_CDD_Procedures.docx",
              Attribute_ID: "A008",
              Attribute_Name: "Sanctions Screening",
              Category: "AML",
              Source: "AML > Screening > OFAC",
              Source_Page: "para 30",
              Question_Text: "Confirm that sanctions screening (OFAC) was performed at onboarding for the entity and all related parties.",
              Notes: "Must screen entity, BOs, and authorized signers",
              Jurisdiction_ID: "ENT",
              RiskScope: "Base",
              IsRequired: "Y",
              DocumentationAgeRule: "",
              Group: "Screening",
            },
            {
              Source_File: "CIP_CDD_Procedures.docx",
              Attribute_ID: "A009",
              Attribute_Name: "PEP Screening",
              Category: "AML",
              Source: "AML > Screening > PEP",
              Source_Page: "para 32",
              Question_Text: "Verify that Politically Exposed Person (PEP) screening was completed for beneficial owners and controlling persons.",
              Notes: "Include domestic and foreign PEPs",
              Jurisdiction_ID: "ENT",
              RiskScope: "Base",
              IsRequired: "Y",
              DocumentationAgeRule: "",
              Group: "Screening",
            },
            {
              Source_File: "CIP_CDD_Procedures.docx",
              Attribute_ID: "A010",
              Attribute_Name: "Adverse Media Screening",
              Category: "AML",
              Source: "AML > Screening > Adverse Media",
              Source_Page: "para 34",
              Question_Text: "Confirm that adverse media screening was performed at onboarding.",
              Notes: "EDD triggers may require enhanced screening",
              Jurisdiction_ID: "ENT",
              RiskScope: "Both",
              IsRequired: "Y",
              DocumentationAgeRule: "",
              Group: "Screening",
            },
          ],
        },
        {
          name: "Acceptable_Docs",
          rows: [
            {
              Source_File: "CIP_CDD_Procedures.docx",
              Attribute_ID: "A001",
              Document_Name: "Certificate of Incorporation",
              Evidence_Source_Document: "Certificate of Incorporation",
              Jurisdiction_ID: "ENT",
              Notes: "Certified copy required",
            },
            {
              Source_File: "CIP_CDD_Procedures.docx",
              Attribute_ID: "A001",
              Document_Name: "Articles of Organization",
              Evidence_Source_Document: "Articles of Organization",
              Jurisdiction_ID: "ENT",
              Notes: "For LLCs",
            },
            {
              Source_File: "CIP_CDD_Procedures.docx",
              Attribute_ID: "A002",
              Document_Name: "IRS Letter 147C",
              Evidence_Source_Document: "IRS Confirmation Letter",
              Jurisdiction_ID: "ENT",
              Notes: "Confirms EIN assignment",
            },
            {
              Source_File: "CIP_CDD_Procedures.docx",
              Attribute_ID: "A002",
              Document_Name: "W-9 Form",
              Evidence_Source_Document: "W-9",
              Jurisdiction_ID: "ENT",
              Notes: "Signed and dated",
            },
            {
              Source_File: "CIP_CDD_Procedures.docx",
              Attribute_ID: "A003",
              Document_Name: "Utility Bill",
              Evidence_Source_Document: "Utility Bill",
              Jurisdiction_ID: "ENT",
              Notes: "Within 90 days",
            },
            {
              Source_File: "CIP_CDD_Procedures.docx",
              Attribute_ID: "A003",
              Document_Name: "Bank Statement",
              Evidence_Source_Document: "Bank Statement",
              Jurisdiction_ID: "ENT",
              Notes: "Within 90 days, shows address",
            },
            {
              Source_File: "CIP_CDD_Procedures.docx",
              Attribute_ID: "A006",
              Document_Name: "Passport Copy",
              Evidence_Source_Document: "Passport",
              Jurisdiction_ID: "ENT",
              Notes: "Unexpired, government-issued photo ID",
            },
            {
              Source_File: "CIP_CDD_Procedures.docx",
              Attribute_ID: "A006",
              Document_Name: "Driver's License",
              Evidence_Source_Document: "Driver's License",
              Jurisdiction_ID: "ENT",
              Notes: "Unexpired, state-issued",
            },
          ],
        },
      ],
    },
  };
}

// Mock response for Standards Comparison (Old GFC vs New GFC)
export function getMockStandardsComparisonResult() {
  return {
    workbook: {
      title: "Standards Comparison — Old GFC vs Current GFC",
      generated_at: new Date().toISOString().split("T")[0],
      sheets: [
        {
          name: "Summary",
          rows: [
            { Metric: "Total Requirements Analyzed", Value: 30 },
            { Metric: "Unchanged", Value: 18 },
            { Metric: "Modified", Value: 7 },
            { Metric: "Removed", Value: 2 },
            { Metric: "New", Value: 3 },
            { Metric: "Relaxed", Value: 0 },
          ],
        },
        {
          name: "Gap_Details",
          rows: [
            {
              Change_ID: "CHG-0001",
              Change_Type: "MODIFIED",
              Impact: "High",
              Old_Requirement_ID: "OLD-STD-005",
              Current_Requirement_ID: "CUR-STD-005",
              Change_Description: "Added explicit verification requirement for beneficial ownership information",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0002",
              Change_Type: "NEW",
              Impact: "High",
              Old_Requirement_ID: "N/A",
              Current_Requirement_ID: "CUR-STD-012",
              Change_Description: "New requirement for jurisdiction-based EDD",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0003",
              Change_Type: "MODIFIED",
              Impact: "Medium",
              Old_Requirement_ID: "OLD-STD-008",
              Current_Requirement_ID: "CUR-STD-008",
              Change_Description: "Added flexibility for timing of CIP information collection",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0004",
              Change_Type: "REMOVED",
              Impact: "Low",
              Old_Requirement_ID: "OLD-STD-022",
              Current_Requirement_ID: "N/A",
              Change_Description: "Removed mandatory site visit requirement for address verification",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0005",
              Change_Type: "NEW",
              Impact: "Medium",
              Old_Requirement_ID: "N/A",
              Current_Requirement_ID: "CUR-STD-025",
              Change_Description: "New requirement for periodic customer risk review",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0006",
              Change_Type: "MODIFIED",
              Impact: "Medium",
              Old_Requirement_ID: "OLD-STD-015",
              Current_Requirement_ID: "CUR-STD-015",
              Change_Description: "Expanded sanctions screening scope and added automation requirement",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0007",
              Change_Type: "UNCHANGED",
              Impact: "Low",
              Old_Requirement_ID: "OLD-STD-001",
              Current_Requirement_ID: "CUR-STD-001",
              Change_Description: "Customer name collection requirement unchanged",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0008",
              Change_Type: "UNCHANGED",
              Impact: "Low",
              Old_Requirement_ID: "OLD-STD-002",
              Current_Requirement_ID: "CUR-STD-002",
              Change_Description: "Date of birth collection requirement unchanged",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0009",
              Change_Type: "UNCHANGED",
              Impact: "Low",
              Old_Requirement_ID: "OLD-STD-003",
              Current_Requirement_ID: "CUR-STD-003",
              Change_Description: "Address collection requirement unchanged",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0010",
              Change_Type: "UNCHANGED",
              Impact: "Low",
              Old_Requirement_ID: "OLD-STD-004",
              Current_Requirement_ID: "CUR-STD-004",
              Change_Description: "SSN/TIN collection requirement unchanged",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0011",
              Change_Type: "MODIFIED",
              Impact: "Medium",
              Old_Requirement_ID: "OLD-STD-006",
              Current_Requirement_ID: "CUR-STD-006",
              Change_Description: "Documentary verification methods expanded to include electronic verification",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0012",
              Change_Type: "UNCHANGED",
              Impact: "Low",
              Old_Requirement_ID: "OLD-STD-007",
              Current_Requirement_ID: "CUR-STD-007",
              Change_Description: "Non-documentary verification methods unchanged",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0013",
              Change_Type: "UNCHANGED",
              Impact: "Low",
              Old_Requirement_ID: "OLD-STD-009",
              Current_Requirement_ID: "CUR-STD-009",
              Change_Description: "Record retention period unchanged at 5 years",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0014",
              Change_Type: "MODIFIED",
              Impact: "Low",
              Old_Requirement_ID: "OLD-STD-010",
              Current_Requirement_ID: "CUR-STD-010",
              Change_Description: "Customer notice timing clarified to include digital delivery",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0015",
              Change_Type: "UNCHANGED",
              Impact: "Low",
              Old_Requirement_ID: "OLD-STD-011",
              Current_Requirement_ID: "CUR-STD-011",
              Change_Description: "Risk rating assignment requirement unchanged",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0016",
              Change_Type: "NEW",
              Impact: "Medium",
              Old_Requirement_ID: "N/A",
              Current_Requirement_ID: "CUR-STD-026",
              Change_Description: "New requirement for adverse media screening at onboarding",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0017",
              Change_Type: "UNCHANGED",
              Impact: "Low",
              Old_Requirement_ID: "OLD-STD-013",
              Current_Requirement_ID: "CUR-STD-013",
              Change_Description: "Entity type documentation requirement unchanged",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0018",
              Change_Type: "UNCHANGED",
              Impact: "Low",
              Old_Requirement_ID: "OLD-STD-014",
              Current_Requirement_ID: "CUR-STD-014",
              Change_Description: "Control person identification requirement unchanged",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0019",
              Change_Type: "MODIFIED",
              Impact: "Medium",
              Old_Requirement_ID: "OLD-STD-016",
              Current_Requirement_ID: "CUR-STD-016",
              Change_Description: "PEP screening expanded to include domestic PEPs",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0020",
              Change_Type: "UNCHANGED",
              Impact: "Low",
              Old_Requirement_ID: "OLD-STD-017",
              Current_Requirement_ID: "CUR-STD-017",
              Change_Description: "EDD source of funds requirement unchanged",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0021",
              Change_Type: "UNCHANGED",
              Impact: "Low",
              Old_Requirement_ID: "OLD-STD-018",
              Current_Requirement_ID: "CUR-STD-018",
              Change_Description: "EDD source of wealth requirement unchanged",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0022",
              Change_Type: "REMOVED",
              Impact: "Low",
              Old_Requirement_ID: "OLD-STD-019",
              Current_Requirement_ID: "N/A",
              Change_Description: "Removed requirement for notarized documents for certain account types",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0023",
              Change_Type: "UNCHANGED",
              Impact: "Low",
              Old_Requirement_ID: "OLD-STD-020",
              Current_Requirement_ID: "CUR-STD-020",
              Change_Description: "Exception approval process unchanged",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0024",
              Change_Type: "UNCHANGED",
              Impact: "Low",
              Old_Requirement_ID: "OLD-STD-021",
              Current_Requirement_ID: "CUR-STD-021",
              Change_Description: "Third-party reliance requirements unchanged",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0025",
              Change_Type: "UNCHANGED",
              Impact: "Low",
              Old_Requirement_ID: "OLD-STD-023",
              Current_Requirement_ID: "CUR-STD-022",
              Change_Description: "SAR escalation requirements unchanged",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0026",
              Change_Type: "UNCHANGED",
              Impact: "Low",
              Old_Requirement_ID: "OLD-STD-024",
              Current_Requirement_ID: "CUR-STD-023",
              Change_Description: "Training requirements unchanged",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0027",
              Change_Type: "UNCHANGED",
              Impact: "Low",
              Old_Requirement_ID: "OLD-STD-025",
              Current_Requirement_ID: "CUR-STD-024",
              Change_Description: "QA testing requirements unchanged",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0028",
              Change_Type: "UNCHANGED",
              Impact: "Low",
              Old_Requirement_ID: "OLD-STD-026",
              Current_Requirement_ID: "CUR-STD-027",
              Change_Description: "Audit trail requirements unchanged",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0029",
              Change_Type: "UNCHANGED",
              Impact: "Low",
              Old_Requirement_ID: "OLD-STD-027",
              Current_Requirement_ID: "CUR-STD-028",
              Change_Description: "Data protection requirements unchanged",
              Confidence: "High",
            },
            {
              Change_ID: "CHG-0030",
              Change_Type: "MODIFIED",
              Impact: "Low",
              Old_Requirement_ID: "OLD-STD-028",
              Current_Requirement_ID: "CUR-STD-029",
              Change_Description: "Reporting requirements updated to include new regulatory forms",
              Confidence: "High",
            },
          ],
        },
      ],
    },
  };
}
