// Mock data for Attribute Library
// Matches the Excel Attribute Library Workbook structure

import type {
  Attribute,
  AcceptableDoc,
  GenerationReviewRow,
  Auditor,
  ClientTypeRisk,
  Jurisdiction,
  SamplingConfig,
  BatchConfig,
} from './types';

// Jurisdictions (4 jurisdictions)
export const mockJurisdictions: Jurisdiction[] = [
  { Jurisdiction_ID: 'ENT', Jurisdiction_Name: 'Enterprise (Global)' },
  { Jurisdiction_ID: 'SG', Jurisdiction_Name: 'Singapore' },
  { Jurisdiction_ID: 'UK', Jurisdiction_Name: 'United Kingdom' },
  { Jurisdiction_ID: 'CA', Jurisdiction_Name: 'Canada' },
];

// Auditors (4 auditors)
export const mockAuditors: Auditor[] = [
  { AuditorID: 'AUD001', AuditorName: 'John Smith', Email: 'john.smith@crowe.com' },
  { AuditorID: 'AUD002', AuditorName: 'Sarah Johnson', Email: 'sarah.johnson@crowe.com' },
  { AuditorID: 'AUD003', AuditorName: 'Michael Chen', Email: 'michael.chen@crowe.com' },
  { AuditorID: 'AUD004', AuditorName: 'Emily Davis', Email: 'emily.davis@crowe.com' },
];

// Client Type Risk Mappings (8 mappings)
export const mockClientTypeRisk: ClientTypeRisk[] = [
  { ClientType: 'Individual - Domestic', RiskTier: 'Low', IsEDD: false },
  { ClientType: 'Individual - Foreign', RiskTier: 'Medium', IsEDD: false },
  { ClientType: 'Corporate - Domestic', RiskTier: 'Low', IsEDD: false },
  { ClientType: 'Corporate - Foreign', RiskTier: 'Medium', IsEDD: false },
  { ClientType: 'PEP', RiskTier: 'High', IsEDD: true },
  { ClientType: 'Trust', RiskTier: 'Medium', IsEDD: false },
  { ClientType: 'Fund', RiskTier: 'High', IsEDD: true },
  { ClientType: 'Correspondent Bank', RiskTier: 'Critical', IsEDD: true },
];

// Attributes (40 attributes)
export const mockAttributes: Attribute[] = [
  // Entity Profile Attributes
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'ENT-001',
    Attribute_Name: 'Legal Name Verification',
    Category: 'Entity Profile',
    Source: 'Global CDD Standard',
    Source_Page: '12',
    Question_Text: 'Is the legal name of the entity verified against official registration documents?',
    Notes: 'Primary identification requirement',
    Jurisdiction_ID: 'ENT',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '365',
    Group: 'Entity',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'ENT-002',
    Attribute_Name: 'Registration Number',
    Category: 'Entity Profile',
    Source: 'Global CDD Standard',
    Source_Page: '12',
    Question_Text: 'Is the entity registration number documented and verified?',
    Notes: '',
    Jurisdiction_ID: 'ENT',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '365',
    Group: 'Entity',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'ENT-003',
    Attribute_Name: 'Business Address',
    Category: 'Entity Profile',
    Source: 'Global CDD Standard',
    Source_Page: '13',
    Question_Text: 'Is the principal place of business address documented?',
    Notes: 'Must match registration documents',
    Jurisdiction_ID: 'ENT',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '180',
    Group: 'Entity',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'ENT-004',
    Attribute_Name: 'Date of Incorporation',
    Category: 'Entity Profile',
    Source: 'Global CDD Standard',
    Source_Page: '13',
    Question_Text: 'Is the date of incorporation/formation documented?',
    Notes: '',
    Jurisdiction_ID: 'ENT',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '',
    Group: 'Entity',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'ENT-005',
    Attribute_Name: 'Entity Type',
    Category: 'Entity Profile',
    Source: 'Global CDD Standard',
    Source_Page: '14',
    Question_Text: 'Is the legal entity type properly classified and documented?',
    Notes: 'Corporation, LLC, Partnership, etc.',
    Jurisdiction_ID: 'ENT',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '',
    Group: 'Entity',
  },
  // Individual Profile Attributes
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'IND-001',
    Attribute_Name: 'Full Legal Name',
    Category: 'Individual Profile',
    Source: 'Global CDD Standard',
    Source_Page: '18',
    Question_Text: 'Is the full legal name of the individual documented?',
    Notes: 'Must match government-issued ID',
    Jurisdiction_ID: 'ENT',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '365',
    Group: 'Individuals',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'IND-002',
    Attribute_Name: 'Date of Birth',
    Category: 'Individual Profile',
    Source: 'Global CDD Standard',
    Source_Page: '18',
    Question_Text: 'Is the date of birth documented and verified?',
    Notes: '',
    Jurisdiction_ID: 'ENT',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '',
    Group: 'Individuals',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'IND-003',
    Attribute_Name: 'Residential Address',
    Category: 'Individual Profile',
    Source: 'Global CDD Standard',
    Source_Page: '19',
    Question_Text: 'Is the current residential address documented?',
    Notes: 'Proof of address required',
    Jurisdiction_ID: 'ENT',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '90',
    Group: 'Individuals',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'IND-004',
    Attribute_Name: 'Nationality',
    Category: 'Individual Profile',
    Source: 'Global CDD Standard',
    Source_Page: '19',
    Question_Text: 'Is the nationality/citizenship documented?',
    Notes: '',
    Jurisdiction_ID: 'ENT',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '',
    Group: 'Individuals',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'IND-005',
    Attribute_Name: 'Government ID',
    Category: 'Individual Profile',
    Source: 'Global CDD Standard',
    Source_Page: '20',
    Question_Text: 'Is a valid government-issued photo ID on file?',
    Notes: 'Passport, National ID, or Drivers License',
    Jurisdiction_ID: 'ENT',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '365',
    Group: 'Individuals',
  },
  // Ownership Attributes
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'OWN-001',
    Attribute_Name: 'Ownership Structure',
    Category: 'Ownership',
    Source: 'Global CDD Standard',
    Source_Page: '25',
    Question_Text: 'Is the ownership structure documented with percentage holdings?',
    Notes: 'Include all owners >25%',
    Jurisdiction_ID: 'ENT',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '365',
    Group: 'Beneficial Owner',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'OWN-002',
    Attribute_Name: 'Ultimate Beneficial Owner',
    Category: 'Ownership',
    Source: 'Global CDD Standard',
    Source_Page: '26',
    Question_Text: 'Are all UBOs (>25% ownership) identified and verified?',
    Notes: 'Must trace through all layers',
    Jurisdiction_ID: 'ENT',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '365',
    Group: 'Beneficial Owner',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'OWN-003',
    Attribute_Name: 'Control Person',
    Category: 'Ownership',
    Source: 'Global CDD Standard',
    Source_Page: '27',
    Question_Text: 'Are individuals with significant control identified?',
    Notes: 'Directors, officers, authorized signers',
    Jurisdiction_ID: 'ENT',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '365',
    Group: 'Beneficial Owner',
  },
  // AML Attributes
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'AML-001',
    Attribute_Name: 'Sanctions Screening',
    Category: 'AML',
    Source: 'Global CDD Standard',
    Source_Page: '32',
    Question_Text: 'Has sanctions screening been performed for all parties?',
    Notes: 'OFAC, UN, EU sanctions lists',
    Jurisdiction_ID: 'ENT',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '',
    Group: 'Screening',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'AML-002',
    Attribute_Name: 'PEP Screening',
    Category: 'AML',
    Source: 'Global CDD Standard',
    Source_Page: '33',
    Question_Text: 'Has PEP screening been performed for all individuals?',
    Notes: 'Include family members and close associates',
    Jurisdiction_ID: 'ENT',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '',
    Group: 'Screening',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'AML-003',
    Attribute_Name: 'Adverse Media',
    Category: 'AML',
    Source: 'Global CDD Standard',
    Source_Page: '34',
    Question_Text: 'Has adverse media screening been conducted?',
    Notes: '',
    Jurisdiction_ID: 'ENT',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '',
    Group: 'Screening',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'AML-004',
    Attribute_Name: 'Risk Rating',
    Category: 'AML',
    Source: 'Global CDD Standard',
    Source_Page: '35',
    Question_Text: 'Is the customer risk rating documented and justified?',
    Notes: 'Low, Medium, High, Critical',
    Jurisdiction_ID: 'ENT',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '',
    Group: 'Screening',
  },
  // EDD Attributes
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'EDD-001',
    Attribute_Name: 'Source of Wealth',
    Category: 'EDD',
    Source: 'Global CDD Standard',
    Source_Page: '40',
    Question_Text: 'Is the source of wealth documented for high-risk customers?',
    Notes: 'Required for EDD cases',
    Jurisdiction_ID: 'ENT',
    RiskScope: 'EDD',
    IsRequired: 'Y',
    DocumentationAgeRule: '365',
    Group: 'Individuals',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'EDD-002',
    Attribute_Name: 'Source of Funds',
    Category: 'EDD',
    Source: 'Global CDD Standard',
    Source_Page: '41',
    Question_Text: 'Is the source of funds for the relationship documented?',
    Notes: 'Required for EDD cases',
    Jurisdiction_ID: 'ENT',
    RiskScope: 'EDD',
    IsRequired: 'Y',
    DocumentationAgeRule: '365',
    Group: 'Entity',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'EDD-003',
    Attribute_Name: 'Enhanced Monitoring',
    Category: 'EDD',
    Source: 'Global CDD Standard',
    Source_Page: '42',
    Question_Text: 'Is there evidence of enhanced transaction monitoring?',
    Notes: '',
    Jurisdiction_ID: 'ENT',
    RiskScope: 'EDD',
    IsRequired: 'Y',
    DocumentationAgeRule: '',
    Group: 'Screening',
  },
  // Singapore-specific attributes
  {
    Source_File: 'MAS_Notice_626.pdf',
    Attribute_ID: 'SG-001',
    Attribute_Name: 'ACRA Search',
    Category: 'Documentation',
    Source: 'MAS Notice 626',
    Source_Page: '8',
    Question_Text: 'Is an ACRA business profile search on file?',
    Notes: 'Singapore entities only',
    Jurisdiction_ID: 'SG',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '180',
    Group: 'Entity',
  },
  {
    Source_File: 'MAS_Notice_626.pdf',
    Attribute_ID: 'SG-002',
    Attribute_Name: 'SG Beneficial Owner Declaration',
    Category: 'Ownership',
    Source: 'MAS Notice 626',
    Source_Page: '12',
    Question_Text: 'Is the MAS BO declaration form completed for SG entities?',
    Notes: '10% threshold for SG',
    Jurisdiction_ID: 'SG',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '365',
    Group: 'Beneficial Owner',
  },
  {
    Source_File: 'MAS_Notice_626.pdf',
    Attribute_ID: 'SG-003',
    Attribute_Name: 'Singpass Verification',
    Category: 'Individual Profile',
    Source: 'MAS Notice 626',
    Source_Page: '15',
    Question_Text: 'For SG citizens/PRs, is Singpass verification completed?',
    Notes: 'Alternative to physical ID copy',
    Jurisdiction_ID: 'SG',
    RiskScope: 'Base',
    IsRequired: 'N',
    DocumentationAgeRule: '',
    Group: 'Individuals',
  },
  {
    Source_File: 'MAS_Notice_626.pdf',
    Attribute_ID: 'SG-004',
    Attribute_Name: 'SG Tax Residency',
    Category: 'Compliance',
    Source: 'MAS Notice 626',
    Source_Page: '18',
    Question_Text: 'Is tax residency self-certification completed for FATCA/CRS?',
    Notes: '',
    Jurisdiction_ID: 'SG',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '',
    Group: 'Entity',
  },
  // UK-specific attributes
  {
    Source_File: 'FCA_SYSC_6.pdf',
    Attribute_ID: 'UK-001',
    Attribute_Name: 'Companies House Search',
    Category: 'Documentation',
    Source: 'FCA SYSC 6',
    Source_Page: '5',
    Question_Text: 'Is a Companies House search on file for UK entities?',
    Notes: 'UK entities only',
    Jurisdiction_ID: 'UK',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '90',
    Group: 'Entity',
  },
  {
    Source_File: 'FCA_SYSC_6.pdf',
    Attribute_ID: 'UK-002',
    Attribute_Name: 'PSC Register',
    Category: 'Ownership',
    Source: 'FCA SYSC 6',
    Source_Page: '8',
    Question_Text: 'Is the PSC (Persons with Significant Control) register reviewed?',
    Notes: 'Must match internal records',
    Jurisdiction_ID: 'UK',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '90',
    Group: 'Beneficial Owner',
  },
  {
    Source_File: 'FCA_SYSC_6.pdf',
    Attribute_ID: 'UK-003',
    Attribute_Name: 'UK Sanctions Check',
    Category: 'AML',
    Source: 'FCA SYSC 6',
    Source_Page: '12',
    Question_Text: 'Is OFSI sanctions list screening documented?',
    Notes: 'UK-specific sanctions list',
    Jurisdiction_ID: 'UK',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '',
    Group: 'Screening',
  },
  {
    Source_File: 'FCA_SYSC_6.pdf',
    Attribute_ID: 'UK-004',
    Attribute_Name: 'UK MLR Compliance',
    Category: 'Compliance',
    Source: 'FCA SYSC 6',
    Source_Page: '15',
    Question_Text: 'Is there documented compliance with UK MLR 2017?',
    Notes: '',
    Jurisdiction_ID: 'UK',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '',
    Group: 'Entity',
  },
  // Canada-specific attributes
  {
    Source_File: 'FINTRAC_Guidance.pdf',
    Attribute_ID: 'CA-001',
    Attribute_Name: 'FINTRAC Registration',
    Category: 'Compliance',
    Source: 'FINTRAC Guidance',
    Source_Page: '6',
    Question_Text: 'For MSBs, is FINTRAC registration confirmed?',
    Notes: 'Canadian MSBs only',
    Jurisdiction_ID: 'CA',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '365',
    Group: 'Entity',
  },
  {
    Source_File: 'FINTRAC_Guidance.pdf',
    Attribute_ID: 'CA-002',
    Attribute_Name: 'SEDAR Search',
    Category: 'Documentation',
    Source: 'FINTRAC Guidance',
    Source_Page: '10',
    Question_Text: 'For public companies, is SEDAR filing reviewed?',
    Notes: 'Canadian public companies',
    Jurisdiction_ID: 'CA',
    RiskScope: 'Base',
    IsRequired: 'N',
    DocumentationAgeRule: '365',
    Group: 'Entity',
  },
  {
    Source_File: 'FINTRAC_Guidance.pdf',
    Attribute_ID: 'CA-003',
    Attribute_Name: 'Canadian ID Verification',
    Category: 'Individual Profile',
    Source: 'FINTRAC Guidance',
    Source_Page: '14',
    Question_Text: 'Is dual-process ID verification completed per FINTRAC rules?',
    Notes: 'Two methods required',
    Jurisdiction_ID: 'CA',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '',
    Group: 'Individuals',
  },
  {
    Source_File: 'FINTRAC_Guidance.pdf',
    Attribute_ID: 'CA-004',
    Attribute_Name: 'CA Beneficial Owner',
    Category: 'Ownership',
    Source: 'FINTRAC Guidance',
    Source_Page: '18',
    Question_Text: 'Are all BOs with 25%+ ownership identified per FINTRAC?',
    Notes: '',
    Jurisdiction_ID: 'CA',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '365',
    Group: 'Beneficial Owner',
  },
  // Additional Global Attributes
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'ENT-006',
    Attribute_Name: 'Nature of Business',
    Category: 'Entity Profile',
    Source: 'Global CDD Standard',
    Source_Page: '14',
    Question_Text: 'Is the nature of business/industry sector documented?',
    Notes: '',
    Jurisdiction_ID: 'ENT',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '',
    Group: 'Entity',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'ENT-007',
    Attribute_Name: 'Expected Activity',
    Category: 'Entity Profile',
    Source: 'Global CDD Standard',
    Source_Page: '15',
    Question_Text: 'Is the expected account activity documented?',
    Notes: 'Volume, frequency, geography',
    Jurisdiction_ID: 'ENT',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '',
    Group: 'Entity',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'ENT-008',
    Attribute_Name: 'Purpose of Relationship',
    Category: 'Entity Profile',
    Source: 'Global CDD Standard',
    Source_Page: '16',
    Question_Text: 'Is the purpose of the business relationship documented?',
    Notes: '',
    Jurisdiction_ID: 'ENT',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '',
    Group: 'Entity',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'IND-006',
    Attribute_Name: 'Occupation',
    Category: 'Individual Profile',
    Source: 'Global CDD Standard',
    Source_Page: '21',
    Question_Text: 'Is the occupation/employer information documented?',
    Notes: '',
    Jurisdiction_ID: 'ENT',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '',
    Group: 'Individuals',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'AML-005',
    Attribute_Name: 'Periodic Review',
    Category: 'AML',
    Source: 'Global CDD Standard',
    Source_Page: '36',
    Question_Text: 'Is there evidence of periodic review per risk tier?',
    Notes: 'High=1yr, Medium=2yr, Low=3yr',
    Jurisdiction_ID: 'ENT',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '',
    Group: 'Screening',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'DOC-001',
    Attribute_Name: 'Certificate of Incorporation',
    Category: 'Documentation',
    Source: 'Global CDD Standard',
    Source_Page: '45',
    Question_Text: 'Is a certified copy of the certificate of incorporation on file?',
    Notes: '',
    Jurisdiction_ID: 'ENT',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '',
    Group: 'Entity',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'DOC-002',
    Attribute_Name: 'Board Resolution',
    Category: 'Documentation',
    Source: 'Global CDD Standard',
    Source_Page: '46',
    Question_Text: 'Is the board resolution for account opening on file?',
    Notes: 'Required for corporations',
    Jurisdiction_ID: 'ENT',
    RiskScope: 'Base',
    IsRequired: 'Y',
    DocumentationAgeRule: '365',
    Group: 'Entity',
  },
];

// Acceptable Documents (86 documents)
export const mockAcceptableDocs: AcceptableDoc[] = [
  // Entity Profile Documents
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'ENT-001',
    Document_Name: 'Certificate of Incorporation',
    Evidence_Source_Document: 'Government Registry',
    Jurisdiction_ID: 'ENT',
    Notes: 'Certified copy required',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'ENT-001',
    Document_Name: 'Certificate of Registration',
    Evidence_Source_Document: 'Government Registry',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'ENT-001',
    Document_Name: 'Trade License',
    Evidence_Source_Document: 'Local Authority',
    Jurisdiction_ID: 'ENT',
    Notes: 'For certain jurisdictions',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'ENT-002',
    Document_Name: 'Certificate of Incorporation',
    Evidence_Source_Document: 'Government Registry',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'ENT-002',
    Document_Name: 'Company Registry Extract',
    Evidence_Source_Document: 'Government Registry',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'ENT-003',
    Document_Name: 'Utility Bill',
    Evidence_Source_Document: 'Utility Provider',
    Jurisdiction_ID: 'ENT',
    Notes: 'Within 90 days',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'ENT-003',
    Document_Name: 'Bank Statement',
    Evidence_Source_Document: 'Financial Institution',
    Jurisdiction_ID: 'ENT',
    Notes: 'Within 90 days',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'ENT-003',
    Document_Name: 'Lease Agreement',
    Evidence_Source_Document: 'Landlord',
    Jurisdiction_ID: 'ENT',
    Notes: 'Current lease',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'ENT-004',
    Document_Name: 'Certificate of Incorporation',
    Evidence_Source_Document: 'Government Registry',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'ENT-005',
    Document_Name: 'Certificate of Incorporation',
    Evidence_Source_Document: 'Government Registry',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'ENT-005',
    Document_Name: 'Articles of Association',
    Evidence_Source_Document: 'Government Registry',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  // Individual Profile Documents
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'IND-001',
    Document_Name: 'Passport',
    Evidence_Source_Document: 'Government',
    Jurisdiction_ID: 'ENT',
    Notes: 'Valid and unexpired',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'IND-001',
    Document_Name: 'National ID Card',
    Evidence_Source_Document: 'Government',
    Jurisdiction_ID: 'ENT',
    Notes: 'With photo',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'IND-001',
    Document_Name: 'Drivers License',
    Evidence_Source_Document: 'Government',
    Jurisdiction_ID: 'ENT',
    Notes: 'With photo',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'IND-002',
    Document_Name: 'Passport',
    Evidence_Source_Document: 'Government',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'IND-002',
    Document_Name: 'Birth Certificate',
    Evidence_Source_Document: 'Government',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'IND-003',
    Document_Name: 'Utility Bill',
    Evidence_Source_Document: 'Utility Provider',
    Jurisdiction_ID: 'ENT',
    Notes: 'Within 90 days',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'IND-003',
    Document_Name: 'Bank Statement',
    Evidence_Source_Document: 'Financial Institution',
    Jurisdiction_ID: 'ENT',
    Notes: 'Within 90 days',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'IND-003',
    Document_Name: 'Government Correspondence',
    Evidence_Source_Document: 'Government',
    Jurisdiction_ID: 'ENT',
    Notes: 'Within 90 days',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'IND-004',
    Document_Name: 'Passport',
    Evidence_Source_Document: 'Government',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'IND-004',
    Document_Name: 'Citizenship Certificate',
    Evidence_Source_Document: 'Government',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'IND-005',
    Document_Name: 'Passport',
    Evidence_Source_Document: 'Government',
    Jurisdiction_ID: 'ENT',
    Notes: 'Valid and unexpired',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'IND-005',
    Document_Name: 'National ID Card',
    Evidence_Source_Document: 'Government',
    Jurisdiction_ID: 'ENT',
    Notes: 'With photo',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'IND-005',
    Document_Name: 'Drivers License',
    Evidence_Source_Document: 'Government',
    Jurisdiction_ID: 'ENT',
    Notes: 'With photo',
  },
  // Ownership Documents
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'OWN-001',
    Document_Name: 'Shareholder Register',
    Evidence_Source_Document: 'Company Records',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'OWN-001',
    Document_Name: 'Share Certificates',
    Evidence_Source_Document: 'Company Records',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'OWN-001',
    Document_Name: 'Organizational Chart',
    Evidence_Source_Document: 'Company Records',
    Jurisdiction_ID: 'ENT',
    Notes: 'With percentages',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'OWN-002',
    Document_Name: 'UBO Declaration Form',
    Evidence_Source_Document: 'Customer Declaration',
    Jurisdiction_ID: 'ENT',
    Notes: 'Signed by authorized person',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'OWN-002',
    Document_Name: 'Ownership Chart',
    Evidence_Source_Document: 'Company Records',
    Jurisdiction_ID: 'ENT',
    Notes: 'All layers traced',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'OWN-003',
    Document_Name: 'Board Resolution',
    Evidence_Source_Document: 'Company Records',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'OWN-003',
    Document_Name: 'Authorized Signatory List',
    Evidence_Source_Document: 'Company Records',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  // AML Documents
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'AML-001',
    Document_Name: 'Sanctions Screening Report',
    Evidence_Source_Document: 'Screening System',
    Jurisdiction_ID: 'ENT',
    Notes: 'All parties screened',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'AML-002',
    Document_Name: 'PEP Screening Report',
    Evidence_Source_Document: 'Screening System',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'AML-003',
    Document_Name: 'Adverse Media Report',
    Evidence_Source_Document: 'Screening System',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'AML-004',
    Document_Name: 'Risk Assessment Form',
    Evidence_Source_Document: 'Internal Assessment',
    Jurisdiction_ID: 'ENT',
    Notes: 'Approved by compliance',
  },
  // EDD Documents
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'EDD-001',
    Document_Name: 'Source of Wealth Declaration',
    Evidence_Source_Document: 'Customer Declaration',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'EDD-001',
    Document_Name: 'Financial Statements',
    Evidence_Source_Document: 'Audited Financials',
    Jurisdiction_ID: 'ENT',
    Notes: 'Last 2 years',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'EDD-001',
    Document_Name: 'Tax Returns',
    Evidence_Source_Document: 'Tax Authority',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'EDD-002',
    Document_Name: 'Source of Funds Declaration',
    Evidence_Source_Document: 'Customer Declaration',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'EDD-002',
    Document_Name: 'Bank Statements',
    Evidence_Source_Document: 'Financial Institution',
    Jurisdiction_ID: 'ENT',
    Notes: 'Last 6 months',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'EDD-003',
    Document_Name: 'Enhanced Monitoring Report',
    Evidence_Source_Document: 'Internal Assessment',
    Jurisdiction_ID: 'ENT',
    Notes: 'Quarterly review',
  },
  // Singapore-specific Documents
  {
    Source_File: 'MAS_Notice_626.pdf',
    Attribute_ID: 'SG-001',
    Document_Name: 'ACRA Business Profile',
    Evidence_Source_Document: 'ACRA',
    Jurisdiction_ID: 'SG',
    Notes: 'Within 180 days',
  },
  {
    Source_File: 'MAS_Notice_626.pdf',
    Attribute_ID: 'SG-001',
    Document_Name: 'ACRA Instant Information',
    Evidence_Source_Document: 'ACRA',
    Jurisdiction_ID: 'SG',
    Notes: '',
  },
  {
    Source_File: 'MAS_Notice_626.pdf',
    Attribute_ID: 'SG-002',
    Document_Name: 'MAS BO Declaration Form',
    Evidence_Source_Document: 'Customer Declaration',
    Jurisdiction_ID: 'SG',
    Notes: '10% threshold',
  },
  {
    Source_File: 'MAS_Notice_626.pdf',
    Attribute_ID: 'SG-003',
    Document_Name: 'Singpass MyInfo Extract',
    Evidence_Source_Document: 'Government',
    Jurisdiction_ID: 'SG',
    Notes: 'Digital verification',
  },
  {
    Source_File: 'MAS_Notice_626.pdf',
    Attribute_ID: 'SG-004',
    Document_Name: 'CRS Self-Certification Form',
    Evidence_Source_Document: 'Customer Declaration',
    Jurisdiction_ID: 'SG',
    Notes: '',
  },
  {
    Source_File: 'MAS_Notice_626.pdf',
    Attribute_ID: 'SG-004',
    Document_Name: 'W-8BEN/W-9',
    Evidence_Source_Document: 'Customer Declaration',
    Jurisdiction_ID: 'SG',
    Notes: 'For US persons',
  },
  // UK-specific Documents
  {
    Source_File: 'FCA_SYSC_6.pdf',
    Attribute_ID: 'UK-001',
    Document_Name: 'Companies House Filing',
    Evidence_Source_Document: 'Companies House',
    Jurisdiction_ID: 'UK',
    Notes: 'Within 90 days',
  },
  {
    Source_File: 'FCA_SYSC_6.pdf',
    Attribute_ID: 'UK-001',
    Document_Name: 'Confirmation Statement',
    Evidence_Source_Document: 'Companies House',
    Jurisdiction_ID: 'UK',
    Notes: 'Annual',
  },
  {
    Source_File: 'FCA_SYSC_6.pdf',
    Attribute_ID: 'UK-002',
    Document_Name: 'PSC Register Extract',
    Evidence_Source_Document: 'Companies House',
    Jurisdiction_ID: 'UK',
    Notes: '',
  },
  {
    Source_File: 'FCA_SYSC_6.pdf',
    Attribute_ID: 'UK-002',
    Document_Name: 'Internal PSC Record',
    Evidence_Source_Document: 'Company Records',
    Jurisdiction_ID: 'UK',
    Notes: 'Must match CH',
  },
  {
    Source_File: 'FCA_SYSC_6.pdf',
    Attribute_ID: 'UK-003',
    Document_Name: 'OFSI Screening Report',
    Evidence_Source_Document: 'Screening System',
    Jurisdiction_ID: 'UK',
    Notes: 'UK sanctions',
  },
  {
    Source_File: 'FCA_SYSC_6.pdf',
    Attribute_ID: 'UK-004',
    Document_Name: 'MLR Compliance Checklist',
    Evidence_Source_Document: 'Internal Assessment',
    Jurisdiction_ID: 'UK',
    Notes: 'MLR 2017',
  },
  // Canada-specific Documents
  {
    Source_File: 'FINTRAC_Guidance.pdf',
    Attribute_ID: 'CA-001',
    Document_Name: 'FINTRAC MSB Registration',
    Evidence_Source_Document: 'FINTRAC',
    Jurisdiction_ID: 'CA',
    Notes: 'If applicable',
  },
  {
    Source_File: 'FINTRAC_Guidance.pdf',
    Attribute_ID: 'CA-002',
    Document_Name: 'SEDAR Filing',
    Evidence_Source_Document: 'SEDAR',
    Jurisdiction_ID: 'CA',
    Notes: 'Public companies',
  },
  {
    Source_File: 'FINTRAC_Guidance.pdf',
    Attribute_ID: 'CA-002',
    Document_Name: 'Annual Report',
    Evidence_Source_Document: 'SEDAR',
    Jurisdiction_ID: 'CA',
    Notes: '',
  },
  {
    Source_File: 'FINTRAC_Guidance.pdf',
    Attribute_ID: 'CA-003',
    Document_Name: 'Credit File Check',
    Evidence_Source_Document: 'Credit Bureau',
    Jurisdiction_ID: 'CA',
    Notes: 'Method 1',
  },
  {
    Source_File: 'FINTRAC_Guidance.pdf',
    Attribute_ID: 'CA-003',
    Document_Name: 'Government Database Check',
    Evidence_Source_Document: 'Government',
    Jurisdiction_ID: 'CA',
    Notes: 'Method 2',
  },
  {
    Source_File: 'FINTRAC_Guidance.pdf',
    Attribute_ID: 'CA-004',
    Document_Name: 'FINTRAC BO Declaration',
    Evidence_Source_Document: 'Customer Declaration',
    Jurisdiction_ID: 'CA',
    Notes: '25% threshold',
  },
  // Additional Global Documents
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'ENT-006',
    Document_Name: 'Business Plan',
    Evidence_Source_Document: 'Company Records',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'ENT-006',
    Document_Name: 'Company Website',
    Evidence_Source_Document: 'Public Source',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'ENT-007',
    Document_Name: 'Expected Activity Form',
    Evidence_Source_Document: 'Customer Declaration',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'ENT-008',
    Document_Name: 'Relationship Purpose Form',
    Evidence_Source_Document: 'Customer Declaration',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'IND-006',
    Document_Name: 'Employment Letter',
    Evidence_Source_Document: 'Employer',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'IND-006',
    Document_Name: 'Business Card',
    Evidence_Source_Document: 'Customer',
    Jurisdiction_ID: 'ENT',
    Notes: 'Supporting doc',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'AML-005',
    Document_Name: 'Periodic Review Form',
    Evidence_Source_Document: 'Internal Assessment',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'AML-005',
    Document_Name: 'Updated KYC Checklist',
    Evidence_Source_Document: 'Internal Assessment',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'DOC-001',
    Document_Name: 'Certified Certificate of Inc',
    Evidence_Source_Document: 'Government Registry',
    Jurisdiction_ID: 'ENT',
    Notes: 'Apostille if foreign',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'DOC-002',
    Document_Name: 'Board Resolution',
    Evidence_Source_Document: 'Company Records',
    Jurisdiction_ID: 'ENT',
    Notes: 'Account opening authority',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'DOC-002',
    Document_Name: 'Corporate Secretary Certificate',
    Evidence_Source_Document: 'Company Records',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  // Additional supporting documents
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'ENT-001',
    Document_Name: 'Certificate of Good Standing',
    Evidence_Source_Document: 'Government Registry',
    Jurisdiction_ID: 'ENT',
    Notes: 'For existing entities',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'ENT-003',
    Document_Name: 'Tax Registration Certificate',
    Evidence_Source_Document: 'Tax Authority',
    Jurisdiction_ID: 'ENT',
    Notes: 'Shows registered address',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'IND-003',
    Document_Name: 'Rental Agreement',
    Evidence_Source_Document: 'Landlord',
    Jurisdiction_ID: 'ENT',
    Notes: 'Current lease',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'OWN-001',
    Document_Name: 'Partnership Agreement',
    Evidence_Source_Document: 'Company Records',
    Jurisdiction_ID: 'ENT',
    Notes: 'For partnerships',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'OWN-002',
    Document_Name: 'Trust Deed',
    Evidence_Source_Document: 'Trustees',
    Jurisdiction_ID: 'ENT',
    Notes: 'For trusts',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'AML-001',
    Document_Name: 'Watchlist Screening',
    Evidence_Source_Document: 'Screening System',
    Jurisdiction_ID: 'ENT',
    Notes: 'All global lists',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'AML-002',
    Document_Name: 'PEP Self-Declaration',
    Evidence_Source_Document: 'Customer Declaration',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'EDD-001',
    Document_Name: 'Investment Portfolio Statement',
    Evidence_Source_Document: 'Financial Institution',
    Jurisdiction_ID: 'ENT',
    Notes: '',
  },
  {
    Source_File: 'Global_Standards_v3.pdf',
    Attribute_ID: 'EDD-002',
    Document_Name: 'Wire Transfer Documentation',
    Evidence_Source_Document: 'Financial Institution',
    Jurisdiction_ID: 'ENT',
    Notes: 'For large transfers',
  },
  {
    Source_File: 'MAS_Notice_626.pdf',
    Attribute_ID: 'SG-001',
    Document_Name: 'Company Constitution',
    Evidence_Source_Document: 'Company Records',
    Jurisdiction_ID: 'SG',
    Notes: 'SG entities',
  },
  {
    Source_File: 'FCA_SYSC_6.pdf',
    Attribute_ID: 'UK-001',
    Document_Name: 'Certificate of Incorporation on Change of Name',
    Evidence_Source_Document: 'Companies House',
    Jurisdiction_ID: 'UK',
    Notes: 'If name changed',
  },
  {
    Source_File: 'FINTRAC_Guidance.pdf',
    Attribute_ID: 'CA-001',
    Document_Name: 'Provincial Business License',
    Evidence_Source_Document: 'Provincial Registry',
    Jurisdiction_ID: 'CA',
    Notes: 'Provincial registration',
  },
  {
    Source_File: 'FINTRAC_Guidance.pdf',
    Attribute_ID: 'CA-003',
    Document_Name: 'Attestation from Commissioner',
    Evidence_Source_Document: 'Third Party',
    Jurisdiction_ID: 'CA',
    Notes: 'Alternative method',
  },
];

// Generation Review Rows (20 samples)
export const mockGenerationReviewRows: GenerationReviewRow[] = [
  {
    Sampling_Index: 1,
    GCI: 'GCI-001234',
    Legal_Name: 'Acme Corporation Ltd',
    Jurisdiction_ID: 'SG',
    Jurisdiction: 'Singapore',
    AuditorID: 'AUD001',
    Auditor_Name: 'John Smith',
    IRR: 3.2,
    DRR: 2.8,
    Party_Type: 'Corporate - Foreign',
    KYC_Date: '2024-06-15',
    Primary_FLU: 'SG-Corporate',
  },
  {
    Sampling_Index: 2,
    GCI: 'GCI-002345',
    Legal_Name: 'Global Trading Partners Inc',
    Jurisdiction_ID: 'UK',
    Jurisdiction: 'United Kingdom',
    AuditorID: 'AUD002',
    Auditor_Name: 'Sarah Johnson',
    IRR: 4.1,
    DRR: 3.5,
    Party_Type: 'Corporate - Domestic',
    KYC_Date: '2024-05-20',
    Primary_FLU: 'UK-Corporate',
  },
  {
    Sampling_Index: 3,
    GCI: 'GCI-003456',
    Legal_Name: 'Chen Wei Holdings Pte Ltd',
    Jurisdiction_ID: 'SG',
    Jurisdiction: 'Singapore',
    AuditorID: 'AUD003',
    Auditor_Name: 'Michael Chen',
    IRR: 2.5,
    DRR: 2.1,
    Party_Type: 'Corporate - Domestic',
    KYC_Date: '2024-07-01',
    Primary_FLU: 'SG-Corporate',
  },
  {
    Sampling_Index: 4,
    GCI: 'GCI-004567',
    Legal_Name: 'Northern Ventures Capital Corp',
    Jurisdiction_ID: 'CA',
    Jurisdiction: 'Canada',
    AuditorID: 'AUD004',
    Auditor_Name: 'Emily Davis',
    IRR: 5.8,
    DRR: 4.9,
    Party_Type: 'Fund',
    KYC_Date: '2024-04-10',
    Primary_FLU: 'CA-Investment',
  },
  {
    Sampling_Index: 5,
    GCI: 'GCI-005678',
    Legal_Name: 'Smith, John Robert',
    Jurisdiction_ID: 'UK',
    Jurisdiction: 'United Kingdom',
    AuditorID: 'AUD001',
    Auditor_Name: 'John Smith',
    IRR: 1.8,
    DRR: 1.5,
    Party_Type: 'Individual - Domestic',
    KYC_Date: '2024-08-05',
    Primary_FLU: 'UK-Retail',
  },
  {
    Sampling_Index: 6,
    GCI: 'GCI-006789',
    Legal_Name: 'Pacific Rim Industries',
    Jurisdiction_ID: 'SG',
    Jurisdiction: 'Singapore',
    AuditorID: 'AUD002',
    Auditor_Name: 'Sarah Johnson',
    IRR: 3.9,
    DRR: 3.2,
    Party_Type: 'Corporate - Foreign',
    KYC_Date: '2024-03-25',
    Primary_FLU: 'SG-Corporate',
  },
  {
    Sampling_Index: 7,
    GCI: 'GCI-007890',
    Legal_Name: 'European Finance Trust',
    Jurisdiction_ID: 'UK',
    Jurisdiction: 'United Kingdom',
    AuditorID: 'AUD003',
    Auditor_Name: 'Michael Chen',
    IRR: 6.2,
    DRR: 5.5,
    Party_Type: 'Trust',
    KYC_Date: '2024-02-18',
    Primary_FLU: 'UK-Trust',
  },
  {
    Sampling_Index: 8,
    GCI: 'GCI-008901',
    Legal_Name: 'Wong Enterprises Ltd',
    Jurisdiction_ID: 'SG',
    Jurisdiction: 'Singapore',
    AuditorID: 'AUD004',
    Auditor_Name: 'Emily Davis',
    IRR: 2.2,
    DRR: 1.9,
    Party_Type: 'Corporate - Domestic',
    KYC_Date: '2024-07-12',
    Primary_FLU: 'SG-Corporate',
  },
  {
    Sampling_Index: 9,
    GCI: 'GCI-009012',
    Legal_Name: 'Garcia, Maria Elena',
    Jurisdiction_ID: 'CA',
    Jurisdiction: 'Canada',
    AuditorID: 'AUD001',
    Auditor_Name: 'John Smith',
    IRR: 7.1,
    DRR: 6.8,
    Party_Type: 'PEP',
    KYC_Date: '2024-01-30',
    Primary_FLU: 'CA-PB',
  },
  {
    Sampling_Index: 10,
    GCI: 'GCI-010123',
    Legal_Name: 'Sterling Bank Correspondence',
    Jurisdiction_ID: 'UK',
    Jurisdiction: 'United Kingdom',
    AuditorID: 'AUD002',
    Auditor_Name: 'Sarah Johnson',
    IRR: 8.5,
    DRR: 8.0,
    Party_Type: 'Correspondent Bank',
    KYC_Date: '2024-06-01',
    Primary_FLU: 'UK-FI',
  },
  {
    Sampling_Index: 11,
    GCI: 'GCI-011234',
    Legal_Name: 'Maple Leaf Manufacturing Co',
    Jurisdiction_ID: 'CA',
    Jurisdiction: 'Canada',
    AuditorID: 'AUD003',
    Auditor_Name: 'Michael Chen',
    IRR: 2.8,
    DRR: 2.3,
    Party_Type: 'Corporate - Domestic',
    KYC_Date: '2024-05-05',
    Primary_FLU: 'CA-Corporate',
  },
  {
    Sampling_Index: 12,
    GCI: 'GCI-012345',
    Legal_Name: 'Asia Pacific Investments Fund',
    Jurisdiction_ID: 'SG',
    Jurisdiction: 'Singapore',
    AuditorID: 'AUD004',
    Auditor_Name: 'Emily Davis',
    IRR: 5.5,
    DRR: 4.8,
    Party_Type: 'Fund',
    KYC_Date: '2024-04-22',
    Primary_FLU: 'SG-Investment',
  },
  {
    Sampling_Index: 13,
    GCI: 'GCI-013456',
    Legal_Name: 'Thompson, David Charles',
    Jurisdiction_ID: 'UK',
    Jurisdiction: 'United Kingdom',
    AuditorID: 'AUD001',
    Auditor_Name: 'John Smith',
    IRR: 1.5,
    DRR: 1.2,
    Party_Type: 'Individual - Domestic',
    KYC_Date: '2024-08-10',
    Primary_FLU: 'UK-Retail',
  },
  {
    Sampling_Index: 14,
    GCI: 'GCI-014567',
    Legal_Name: 'Lee Family Office Pte Ltd',
    Jurisdiction_ID: 'SG',
    Jurisdiction: 'Singapore',
    AuditorID: 'AUD002',
    Auditor_Name: 'Sarah Johnson',
    IRR: 4.5,
    DRR: 3.9,
    Party_Type: 'Trust',
    KYC_Date: '2024-03-08',
    Primary_FLU: 'SG-PB',
  },
  {
    Sampling_Index: 15,
    GCI: 'GCI-015678',
    Legal_Name: 'Vancouver Tech Solutions Inc',
    Jurisdiction_ID: 'CA',
    Jurisdiction: 'Canada',
    AuditorID: 'AUD003',
    Auditor_Name: 'Michael Chen',
    IRR: 3.0,
    DRR: 2.5,
    Party_Type: 'Corporate - Domestic',
    KYC_Date: '2024-06-28',
    Primary_FLU: 'CA-Corporate',
  },
  {
    Sampling_Index: 16,
    GCI: 'GCI-016789',
    Legal_Name: 'London Wealth Advisors LLP',
    Jurisdiction_ID: 'UK',
    Jurisdiction: 'United Kingdom',
    AuditorID: 'AUD004',
    Auditor_Name: 'Emily Davis',
    IRR: 4.8,
    DRR: 4.2,
    Party_Type: 'Corporate - Domestic',
    KYC_Date: '2024-02-14',
    Primary_FLU: 'UK-Corporate',
  },
  {
    Sampling_Index: 17,
    GCI: 'GCI-017890',
    Legal_Name: 'Tan, Andrew Ming',
    Jurisdiction_ID: 'SG',
    Jurisdiction: 'Singapore',
    AuditorID: 'AUD001',
    Auditor_Name: 'John Smith',
    IRR: 6.5,
    DRR: 6.0,
    Party_Type: 'PEP',
    KYC_Date: '2024-01-15',
    Primary_FLU: 'SG-PB',
  },
  {
    Sampling_Index: 18,
    GCI: 'GCI-018901',
    Legal_Name: 'Quebec Infrastructure Fund',
    Jurisdiction_ID: 'CA',
    Jurisdiction: 'Canada',
    AuditorID: 'AUD002',
    Auditor_Name: 'Sarah Johnson',
    IRR: 5.2,
    DRR: 4.5,
    Party_Type: 'Fund',
    KYC_Date: '2024-04-18',
    Primary_FLU: 'CA-Investment',
  },
  {
    Sampling_Index: 19,
    GCI: 'GCI-019012',
    Legal_Name: 'British Commerce Holdings plc',
    Jurisdiction_ID: 'UK',
    Jurisdiction: 'United Kingdom',
    AuditorID: 'AUD003',
    Auditor_Name: 'Michael Chen',
    IRR: 3.5,
    DRR: 2.9,
    Party_Type: 'Corporate - Domestic',
    KYC_Date: '2024-05-30',
    Primary_FLU: 'UK-Corporate',
  },
  {
    Sampling_Index: 20,
    GCI: 'GCI-020123',
    Legal_Name: 'Singapore Maritime Services Pte Ltd',
    Jurisdiction_ID: 'SG',
    Jurisdiction: 'Singapore',
    AuditorID: 'AUD004',
    Auditor_Name: 'Emily Davis',
    IRR: 3.8,
    DRR: 3.3,
    Party_Type: 'Corporate - Domestic',
    KYC_Date: '2024-07-25',
    Primary_FLU: 'SG-Corporate',
  },
];

// Sampling Configuration
export const mockSamplingConfig: SamplingConfig = {
  BatchID: 'BATCH-2024-Q3-001',
  SamplingMethod: 'Stratified',
  ConfidenceLevel: 95,
  MarginOfError: 5,
  SampleSize: 20,
  PopulationSize: 1250,
  LockedDate: '2024-08-01',
  Status: 'Locked',
};

// Batch Configuration
export const mockBatchConfig: BatchConfig = {
  BatchID: 'BATCH-2024-Q3-001',
  LastRefresh: '2024-08-15T14:30:00Z',
  OutputFolder: 'C:\\AuditWorkbooks\\2024-Q3',
  Status: 'Ready',
  TotalSamples: 20,
  AssignedCount: 20,
  UnassignedCount: 0,
};

// Helper functions
export function getAttributesByJurisdiction(jurisdictionId: string): Attribute[] {
  return mockAttributes.filter(
    (attr) => attr.Jurisdiction_ID === jurisdictionId || attr.Jurisdiction_ID === 'ENT'
  );
}

export function getAcceptableDocsForAttribute(attributeId: string): AcceptableDoc[] {
  return mockAcceptableDocs.filter((doc) => doc.Attribute_ID === attributeId);
}

export function getAuditorById(auditorId: string): Auditor | undefined {
  return mockAuditors.find((aud) => aud.AuditorID === auditorId);
}

export function getJurisdictionById(jurisdictionId: string): Jurisdiction | undefined {
  return mockJurisdictions.find((j) => j.Jurisdiction_ID === jurisdictionId);
}

export function getClientTypeRisk(clientType: string): ClientTypeRisk | undefined {
  return mockClientTypeRisk.find((ctr) => ctr.ClientType === clientType);
}

// Summary statistics
export function getAttributeLibrarySummary() {
  const categories = [...new Set(mockAttributes.map((a) => a.Category))];
  const groups = [...new Set(mockAttributes.map((a) => a.Group))];

  return {
    totalAttributes: mockAttributes.length,
    totalAcceptableDocs: mockAcceptableDocs.length,
    totalJurisdictions: mockJurisdictions.length,
    totalAuditors: mockAuditors.length,
    totalClientTypeRisks: mockClientTypeRisk.length,
    totalSamples: mockGenerationReviewRows.length,
    categories,
    groups,
    requiredAttributes: mockAttributes.filter((a) => a.IsRequired === 'Y').length,
    eddAttributes: mockAttributes.filter((a) => a.RiskScope === 'EDD' || a.RiskScope === 'Both').length,
  };
}
